### ISSUE TITLE
Use cmake as build_require

### ISSUE THREAD

**Issue by memsharded** [theirix/conan-jsoncpp#5]
Hi @theirix 

In your recipe: 

```python
def requirements(self):
        if self.options.use_cmake_installer:
            self.requires.add("cmake_installer/0.1@lasote/stable", private=False)
```

Having ``use_cmake_installer`` as an option, generates a different package ID. 
For this purpose you better use ``build_requires`` which can be declared in the recipe, or in this case, I would assume that most people building this will have it installed in the system, or can manage it as a ``build_require`` in their conan ``profiles``

**Comment by memsharded** [comment]
Also, when using it, it might turn that:

```python
if self.options.use_cmake_installer:
            cmake_path = os.path.join(self.deps_cpp_info["cmake_installer"].bin_paths[0], 'cmake')
```
is unnecessary, as the tool will already put itself in the path, pre-pending to the system path, so that of the tool will be found first.

**Comment by memsharded** [comment]
And:

```python
        if self.options.use_cmake_installer and self.deps_cpp_info["cmake_installer"].libdirs:
            self.deps_cpp_info["cmake_installer"].libdirs = []
```
Is also unnecessary, as ``build_requires`` do not propagate downstream transitively

**Comment by theirix** [comment]
Hello, @memsharded .
Thank you for the review.

Dependency to cmake was required initially because jsoncpp needs at least cmake 3.1 and CentOS support is needed.
I missed a fact that a build requirement can be specified at a profile, thanks for pointing out. Just tested it on a CentOS 6 with an old cmake 2.8 and it works perfectly. Removed this option from the conanfile in a latest commit. It is much cleaner to specify cmake dependency outside of package.
